[package]
name = "av1_enc"
version = "0.1.0"
edition = "2021"

[dependencies]
walkdir = "2.3"
rayon = "1.7"
indicatif = "0.17"
clap = { version = "4.4", features = ["derive"] }
num_cpus = "1.16"
regex = "1.10"
serde_json = "1.0"
crossbeam-channel = "0.5"
